### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by nannanliuliuliu** [fabianbormann/Tensorflow_Segmentation#29]
Traceback (most recent call last):
  File "img_to_tfrecords.py", line 48, in <module>
    iQ,imgLen,mQ,segLen=read_filelist(args.imgpath,args.segpath)  
  File "img_to_tfrecords.py", line 20, in read_filelist
    imgFiles=tf.train.string_input_producer(imgList,shuffle=False)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/input.py", line 217, in string_input_producer
    raise ValueError(not_null_err)
ValueError: string_input_producer requires a non-null input tensor

**Comment by fabianbormann** [comment]
closed by e4d59e9 (see new batch generator)
